# -*- coding: utf-8 -*-
"""práctica de repaso de clase 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MvsaVclufatBbWzvJRGJWR67MYW1JHO
"""

from typing import Sized
""" 
Utilice colab y pruebe estos operadores básicos.
operadores
Sumar, restar, multiplicar, dividir, potencia de números
Variables
Realice un pequeño programita donde utilice una asignación de variable
Funciones en Python
Defina una lista y con una función sume un valor fijo a cada elemento de la lista y
retorne la nueva lista encontrada.
Suba al campus los ejercicios realizados.

"""

lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Suma
def suma(num, lista):
  listaSuma = lista.copy()
  for i in range(len(lista)):
    listaSuma[i] += num
  return print ("Suma:\n"+ str(listaSuma)+ "\n")

# Resta
def resta(num, lista):
  listaResta = lista.copy()  
  for i in range(len(lista)):
    listaResta[i] -= num
  return print ("Resta:\n"+ str(listaResta)+ "\n")

# Multiplicar
def multiplicar(num, lista):
  listaMultiplicar = lista.copy()
  for i in range(len(lista)):
    listaMultiplicar[i] *= num
  return print ("Multiplicar:\n"+ str(listaMultiplicar)+ "\n")

# Dividir
def dividir(num, lista):
  listaDividir = lista.copy()
  for i in range(len(lista)):
    listaDividir[i] /= num
  return print ("Dividir:\n"+ str(listaDividir)+ "\n")

# Potencia
def potencia(num, lista):
  listaPotencia = lista.copy()
  for i in range(len(lista)):
    listaPotencia[i] **= num
  return print ("Potencia:\n"+ str(listaPotencia)+ "\n")

print("Lista Control: \n" + str(lista)+ "\n")
suma(2, lista)
resta(2, lista)
multiplicar(2, lista)
dividir(2, lista)
potencia(2, lista)